export const DRINKS_PRICES: Record<string, number> = {
  "Chopp Pilsen": 12,
  "Chopp Mutum": 20,
  "Long Neck Heineken/Corona": 15,
  "Energético": 15,
  "Refrigerante": 6,
  "Água": 5,
  "Dose Gin": 10,
  "Dose Jagermeister": 20,
  "Dose Whiskey": 20,
  "Dose Campari": 10,
  "Dose Rum": 15,
"Vinho Cordero": 89,
"Vinho Caoba": 69,
  "Carteira de Cigarro": 15,
};