import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./gentlemen.css";
import "./bootstrap-icons.css";
import "./bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <meta name="description" content=""/>
    <meta name="author" content=""/>

    <title>Gentlemen MC</title>

    <link rel="preconnect" href="https://fonts.googleapis.com"/>

    <link rel="preconnect" href="https://fonts.gstatic.com"/>

    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;400;700&display=swap" rel="stylesheet"/>

    <link href="css/bootstrap.min.css" rel="stylesheet"/>

    <link href="css/bootstrap-icons.css" rel="stylesheet"/>

    <link href="css/gentlemen.css" rel="stylesheet"/>

</head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
